Cap 11 - Historial
jamesvv27/html5 pull request #12
Opened 2024-12-02 22:37 UTC by jamesvv27

## what

* `cap-11/README.md`: Resumen del Capítulo 11 del curso de HTML5.
* `cap-11/src`: Ejemplos de código.
* `cap-11/images`: Screenshots de visualización del ejemplo de código.

## why

* Realizado resumen y ejemplo de código para la implementación del API de historial

## notes

* Visita el capítulo del curso [aquí](https://diveinto.html5doctor.com/history.html)

2024-12-03 00:00 UTC, semanticmx requested changes
muy bien!

2024-12-03 00:00 UTC, semanticmx commented on cap-11/README.md
> +			id="photoimg"
vamos a poner estos en orden alfabético por favor, de esta forma:

```html
			alt="Fer"
			height="375"
                         id="photoimg" 
                         src="gallery/1972-fer-500.jpg"
			width="500"
```

La idea es que si llegaras a tener muchos atributos y quieres agregar uno nuevo, puedas identificar fácilmente que el atributo ya existe.

2024-12-03 15:17 UTC, jamesvv27 commented on cap-11/README.md
> +			id="photoimg"
Listo 👍

2024-12-03 17:01 UTC, ElizaMejia approved these changes

2024-12-10 22:38 UTC, semanticmx approved these changes

2024-12-10 22:39 UTC, merged