Capítulo 2
jamesvv27/html5 pull request #3
Opened 2024-10-08 03:34 UTC by jamesvv27

Agregado resumen de capítulo 2 de HTML5 y README en la raíz con un índice

2024-10-08 13:50 UTC, semanticmx submitted a review, later dismissed
muy bien!

2024-10-08 13:50 UTC, semanticmx commented on cap-02/README.md
> +## Adentrandose
Falta el acento

2024-10-08 15:13 UTC, jamesvv27 commented on README.md
> +0. [Introducción](cap-00/README.md)
La referencia empezará a servir cuando se mezcle con el main

2024-10-08 15:16 UTC, jamesvv27 commented on README.md
> +Para leer el curso completo, [visita la página del libro](https://diveinto.html5doctor.com/index.html)
Claro.

2024-10-08 15:18 UTC, jamesvv27 commented on cap-02/README.md
> +## Adentrandose
Resuelto

2024-10-08 15:28 UTC, ElizaMejia approved these changes
Bien :)

2024-10-08 23:13 UTC, semanticmx requested changes
muy bien!

solo dos correcciones ortográficas y queda

2024-10-08 23:13 UTC, semanticmx commented on README.md
> +Este es un resumen del libro **Adentrandose a HTML5** por Mark Pilgrim
Adentrándose

2024-10-08 23:13 UTC, semanticmx commented on cap-02/README.md
> +El _API del historial HTML5_ es un método para manipular el historial del navegadr con scripts.
navegadr

2024-10-09 19:30 UTC, semanticmx approved these changes
gracias!

2024-10-09 19:42 UTC, merged