Cap 03 Semanticas
jamesvv27/html5 pull request #4
Opened 2024-10-08 21:02 UTC by jamesvv27

Agregado resumen md al capítulo 3 de HTML5

2024-10-08 23:36 UTC, semanticmx requested changes
muy bien, ya puedes ir agregando un folder src/ con el archivo index.html para que implementes los ejemplos de código en el html y tomes un screenshot para que veamos como se ve implementado y corriendo en el navegador.

2024-10-08 23:36 UTC, semanticmx commented on cap-03/README.md
> +    <html xmlns="http://www.w3.org/1999/xhtml"
muy bien!

2024-10-08 23:36 UTC, semanticmx commented on cap-03/README.md
> +     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
acá faltó colocar los atributos en diferentes líneas

2024-10-08 23:36 UTC, semanticmx commented on cap-03/README.md
> +    <link rel="alternate"
como aquí

2024-10-08 23:36 UTC, semanticmx commented on cap-03/README.md
> +    <head>
hay que agregar espacios para identar el código

2024-10-08 23:36 UTC, semanticmx commented on cap-03/README.md
> +    <div class="entry">
muy bien!

2024-10-08 23:46 UTC, ElizaMejia reviewed
Puedes ir haciendo ejemplos en una página con extensión html, subir en un directorio y referenciar desde el resumen ejemplo, "Ver ejemplo en la página EjemposC1.html que se encuentra en el directorio Ejemplos"

2024-10-08 23:46 UTC, ElizaMejia commented on cap-03/README.md
> +    <html>
Falta identar

2024-10-09 19:31 UTC, semanticmx approved these changes
gracias!

2024-10-09 20:03 UTC, semanticmx requested changes

2024-10-09 20:03 UTC, semanticmx commented on cap-03/src/index.html
> +	       <p>&#169; 2001&#8211;9 <a href="#">Mark Pilgrim</a></p>
aquí se ocupa aplicar formato al código.

2024-10-10 15:38 UTC, semanticmx approved these changes
gracias!

2024-10-11 20:47 UTC, ElizaMejia approved these changes
Bien 💯

2024-10-14 16:17 UTC, merged