Capítulo 4 Canvas
jamesvv27/html5 pull request #5
Opened 2024-10-16 16:36 UTC by jamesvv27

Cuarto capítulo del curso de HTML5, con un código de los ejercicios y sus respectivos screenshots

2024-10-16 17:50 UTC, ElizaMejia commented on cap-04/README.md
> +	context.moveTo(260, 40);
Pueden estar alineadas todas si tienen la misma jerarquía

2024-10-16 17:50 UTC, ElizaMejia commented on cap-04/README.md
> +	};
}: está cerrando la función window.onload = fuction() por lo cual la llave tiene que ir antes no a la misma altura de la etiqueta script

<img width="443" alt="Screenshot 2024-10-16 at 11 36 59 a m" src="https://github.com/user-attachments/assets/3bfb99d4-c90a-4ed0-a661-ddce5d5018ad">

2024-10-16 17:50 UTC, ElizaMejia commented on cap-04/README.md
> +  		cat.onload = function() {
tienes una función dentro del script pero no tienes identación correcta, observa la imágen se entiende mejor el script

<img width="383" alt="Screenshot 2024-10-16 at 11 44 43 a m" src="https://github.com/user-attachments/assets/81b29790-1287-408a-b1f1-2fdb1b30d087">

2024-10-16 17:50 UTC, ElizaMejia commented on cap-04/src/index.html
> +            </canvas>
Está mal la identación observa las etiquetas de apertura y cierre de canvas

2024-10-17 04:50 UTC, semanticmx commented
@jamesvv27 podrías por favor agregar una plantilla para los PR's?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

El contenido puede ser en este formato:

```
## what

* Listado de features incluidos en el PR
* Listado de features incluidos en el PR

## why

* Valor de negocio aportado con los cambios

## notes

- Notas adicionales
- Como referencias al issue
- O referencias a la documentación
```

2024-10-17 04:53 UTC, semanticmx requested changes
muy bien!

2024-10-17 04:53 UTC, semanticmx commented on cap-04/src/index.html
> +        <h2 id = "canvas-a">Canvas a - Vacío</h2>
entre los atributos no debe de haber espacios.

debe quedar así: `<h2 id="canvas-a">`

2024-10-17 04:53 UTC, semanticmx commented on cap-04/src/index.html
> +        <canvas id="a"
muy bien!

2024-10-17 04:53 UTC, semanticmx commented on cap-04/src/index.html
> +        <canvas id="c1"
Algunos estilos también lo hacen de esta forma:

```html
<canvas id="c1"
            onclick="get_c1();
            draw_path();
            draw_text()" 
            width="500" 
            height="375"
>
```

Para indicar mejor donde inicia y donde cierra la etiqueta.

2024-10-21 20:57 UTC, semanticmx approved these changes
gracias

2024-10-22 15:13 UTC, ElizaMejia approved these changes
Bien

2024-10-22 15:55 UTC, merged