Capítulo 5 Vídeo
jamesvv27/html5 pull request #6
Opened 2024-10-31 01:27 UTC by jamesvv27

## what

* `cap-05/README.md`: Resumen del Capítulo 5 del curso de HTML5.
* `cap-05/src`: Ejemplo de código con archivos de vídeo adjuntados
* `cap-05/images`: Screenshot de visualización del ejemplo de código

## why

* Se realizó un resumen junto a un ejemplo de código para comprobar la funcionalidad y compatibilidad de los containers y códecs  de audio y vídeo en páginas web.

## notes

* Visita el capítulo del curso [aquí](https://diveinto.html5doctor.com/video.html)

2024-10-31 01:32 UTC, semanticmx requested changes

2024-10-31 01:32 UTC, semanticmx commented on cap-05/README.md
> +    <video src="pr6.webm"></video>
hay que ponerle sus tres acentos invertidos con el nombre del lenguaje para que salga en colores

2024-10-31 01:32 UTC, semanticmx commented on cap-05/src/index.html
> +            <source src="videos/elsenor.mp4" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
y hay que separar los atributos cuando sean más de uno

https://github.com/semanticmx/html5-coding-standards?tab=readme-ov-file#proper-use-of-standards-in-html5

2024-10-31 20:08 UTC, ElizaMejia commented on cap-05/README.md
> +    </video>
Cuida la indentación. Si las etiquetas de "source" tienen el mismo valor dentro de "video", pueden estar alineadas. Así mismo, desde aquí corrige los atributos; si hay más de uno, colócalos en lista
<img width="515" alt="Screenshot 2024-10-31 at 2 08 17 p m" src="https://github.com/user-attachments/assets/6bd36a76-26f8-482f-aea1-7f0a7d512667">

2024-11-04 22:15 UTC, ElizaMejia approved these changes
Bien

2024-11-05 15:54 UTC, semanticmx requested changes

2024-11-05 15:54 UTC, semanticmx commented on cap-05/README.md
> +    <video width="320" height="240">
aquí hay dos atributos en la etiqueta `video`, por lo que si los separamos:

```html
<video 
  width="320" 
  height="240"
>
```

2024-11-05 15:54 UTC, semanticmx commented on cap-05/README.md
> +    		<source
muy bien

2024-11-05 15:54 UTC, semanticmx commented on cap-05/src/index.html
> +<!DOCTYPE html>
muy bien

2024-11-05 18:00 UTC, semanticmx commented on cap-05/src/index.html
> +        <video width="640" height="480" controls>
te faltó esta línea

2024-11-05 18:01 UTC, semanticmx approved these changes
gracias!, los comentarios pendientes los puedes aplicar en el siguiente PR

2024-11-05 18:15 UTC, merged